### ISSUE TITLE
Add support for more than 50 episodes

### ISSUE THREAD

**Issue by palladidrago** [timdorr/spotifeed#10]
Feeds only return 50 episodes in my experience.
Since there are podcasts with thousands of episodes it would be great to have more, or maybe self host and change that number manually.

**Comment by Oravore** [comment]
I agree I also seem to be having this issue as well.

**Comment by MidnightSheep** [comment]
Fully support this. Maybe an option in the site on how many episodes we can select.

**Comment by timdorr** [comment]
I have no plans to add this. 50 is the max number of episodes returned by Spotify's API in a single call. I don't want to burden their API by making excessive requests, nor do I want to get rate limited. Until they raise that limit, I can't risk the cost of multiple API calls.

**Comment by Bobdad1** [comment]
I don't think there is any issue with requesting any number of episodes. I use Spotify's API to filter my music, and I make thousands of calls no problem. I don't know if you're familiar with Python syntax, but [here's](https://onlinegdb.com/SyWf3JSJO) more or less how I went about it (except I did it with music, not podcasts, which are unavailable in my country). As you can see, the `get_show_episodes` function is wrapped inside a decorator which makes sure that all the items are accumulated by making it recur until there are no new items to speak of. If some API-related errors do arise, they can be bypassed by refreshing the token.
