### ISSUE TITLE
What is anon-podcast.scdn.co ?

### ISSUE THREAD

**Issue by Bobdad1** [timdorr/spotifeed#13]
How is it that you get access to the full recording of a podcast episode? I take it that you grab the last part of the **preview url** of the episode as per Spotify's API response and add it onto the _anon-podcast.scdn.co/_. But how does that happen? What is this domain? Is this possible with any episode of the podcast or only the last fifty?

**Comment by timdorr** [comment]
That's the CDN URL used in their podcast preview embed widget. They let you freely listen to any episode in full using that widget without an account needed. [They use the same URL format as the preview URL from the API.](https://github.com/timdorr/spotifeed/blob/master/spotifeed.rb#L78). It works with any podcast episode as far as I can tell.
