### ISSUE TITLE
Does new episodes get rid of old?

### ISSUE THREAD

**Issue by DovahClown** [timdorr/spotifeed#14]
It seems that the feed only supports initially 50 episodes. If a new episode comes out, will the oldest episode in the feed disappear to keep the feed to only being 50 episodes?

**Comment by SEQUOiA87** [comment]
Yes, that's how it works. But some podcast player (like Pocket Casts, I think) keep displaying old episodes.

**Comment by DovahClown** [comment]
Thanks, Can anyone confirm Pocket Casts doesn’t delete the old episodes?

**Comment by timdorr** [comment]
Any app that hasn't blocked the service, such as Pocket Casts, may keep a copy of episodes that have fallen off the feed. My app of choice, Podcast Addict, keeps a cache locally. That's entirely up to your app to implement, however. 

For now, I'm not grabbing more than 50 episodes out of concern for resource usage with Spotify. I don't want to get blocked by them as well, so I want to keep my usage of their service as light as I possibly can.
