### ISSUE TITLE
No new episodes

### ISSUE THREAD

**Issue by emufan** [timdorr/spotifeed#15]
Is there a bug or 
is this related to the 50 items
or a limitation with pocket casts or
something wrong on my side, that

the service shows me the a correct listing for https://open.spotify.com/show/1OLcQdw2PFDPG1jo3s0wbp, but pocket casts shows only the last episode for November 3rd. No single item is shown newer than this, even. No updates on this, even if i archived the 50 received episodes till November 3rd.

**Comment by SEQUOiA87** [comment]
Please see #5...
