### ISSUE TITLE
Incorrect length in enclosure

### ISSUE THREAD

**Issue by neodyne** [timdorr/spotifeed#16]
According to the [RSS spec](https://www.rssboard.org/rss-profile#element-channel-item-enclosure):

> The length attribute indicates the size of the file in bytes.

Currently, spotifeed uses `duration_ms` from the API as enclosure length, which is wrong. As we don't know the size of any particular episode beforehand, from the same doc:

> When an enclosure's size cannot be determined, a publisher should use a length of 0.

[This](https://github.com/timdorr/spotifeed/blob/master/spotifeed.rb#L79) should be `item.enclosure.length = 0`.

**Comment by timdorr** [comment]
Thanks, just put a fix in for that.
