### ISSUE TITLE
How to increase 50 episode limit on self hosted

### ISSUE THREAD

**Issue by c-lgrant** [timdorr/spotifeed#17]
Hey as the title suggests could you please provide some info on how I could increase the 50 episode limit for self hosted.

I have seen your response on issue #10, which is fair enough but could you provide option for this to be changed on self hosted version. 

Thanks

**Comment by timdorr** [comment]
You would need to call [the show episodes endpoint](https://developer.spotify.com/documentation/web-api/reference/#endpoint-get-a-shows-episodes) in a loop after getting the initial show data. There isn't a small tweak to implement this. You'll have to add some new code to make it work.
