### ISSUE TITLE
Doesn't work with iTunes!?

### ISSUE THREAD

**Issue by grizzee** [timdorr/spotifeed#18]
I wanted to add a feed wich i converted with Spotifeed to my iTunes (12.8.2.3, MacOS 10.13.6) but the Feed in iTunes shows "No Episodes in the podcastfeed". 

The Feed works good in Pocketcasts for example.

**Comment by timdorr** [comment]
I just added one in the Podcasts macOS app without issue. I'm not sure about iTunes, since it's been discontinued on macOS.
