### ISSUE TITLE
Episode not downloadable -  Podcast

### ISSUE THREAD

**Issue by BKrnk1337** [timdorr/spotifeed#21]
Thank you for your great service. Working really smooth for me. I have an issue. I can't download episodes in the official Apple podcast app after I added them with your service.
In others podcatcher App it works really
Good. Everything else works fine in the Apple podcast app.

**Comment by BKrnk1337** [comment]
It is this podcast.

https://open.spotify.com/show/7w2wmS5tdwLBMtEN3puAxn?si=2S4yguXTQgWatuXhvBwpDg

**Comment by daurdraug** [comment]
I think if you remove "?si=2S4yguXTQgWatuXhvBwpDg" it will work fine

https://spotifeed.timdorr.com/7w2wmS5tdwLBMtEN3puAxn

**Comment by BKrnk1337** [comment]
Thank you for the reply. The behaviour did not change. Adding and listening is working fine but just download is not working

**Comment by timdorr** [comment]
Sounds like an issue with Apple Podcasts. If I have a tag missing or incorrect, that might be the cause. But I have used Apple Podcasts successfully with other podcasts before, so I'm going to chalk it up to being a client issue. That's out of my hands to fix.

**Comment by BKrnk1337** [comment]
Thanks for the reply. Sad but ok.
