### ISSUE TITLE
Episode URLs 404ing

### ISSUE THREAD

**Issue by whispy** [timdorr/spotifeed#23]
I cannot stream or download a podcast. I have tried with both the Apple Podcasts app and AntennaPod (Android). Both apps give errors when trying to download or stream the feed. Additionally, I have opened the Spotifeed URL's RSS feed and tried to directly open the episodes' URL (e.g https://anon-podcast.scdn.co/ URLs). They 404.

Example:
- Spotify URL: https://open.spotify.com/show/3IKbkJpylxBFb8PWcliJOJ
- Spotifeed URL: https://spotifeed.timdorr.com/3IKbkJpylxBFb8PWcliJOJ

I'm happy to provide more info to help troubleshoot, if needed.

**Comment by whispy** [comment]
I've confirmed this is not a dupe of #21, as the episode URLs in #21 do **not** 404.

**Comment by whispy** [comment]
@timdorr, I believe I've found the issue — Spotify does not host this podcast. Instead, it's hosted by Podbean.

I played the podcast in the Spotify app and proxied my connection through Charles. With that, I was able to find that the URL Spotify is streaming episode one from is: https://mcdn.podbean.com/mf/web/bpvips/EPISODE_ONE_-_MASTERED.mp3

Perhaps Spotifeed could be updated to acommodate this. Otherwise, it should throw some sort of warning/error.

Also, I am not sure if this is a rare occurrence or if Spotify regularly streams podcasts from other hosts.

**Comment by whispy** [comment]
Darn, perhaps that is not it — that podbean.com URL is 404ing...

**Comment by augusto-herrmann** [comment]
All URLs in [this feed](https://spotifeed.timdorr.com/6WRTzGhq3uFxMrxHrHh1lo) have suddenly started to give 410 Gone errors. [Example](https://anon-podcast.scdn.co/da0e5b95c598a283c407ddfc65829c022351668d).

**Comment by timdorr** [comment]
Yeah, looks like https://anon-podcast.scdn.co/ has been discontinued. I'll try to find an alternative, but this may be an issue that prevents Spotifeed from working.

**Comment by thiagoarrais** [comment]
Got hit by that too, @augusto-herrmann. Not sure if this is related to the original issue, though.

**Comment by timdorr** [comment]
Can't seem to find an option that wouldn't involve re-hosting content, which is unfeasible from a cost and legal perspective.

Party's over. Sorry folks, but Spotifeed is dead :(
