### ISSUE TITLE
Add artwork

### ISSUE THREAD

**Issue by distantnative** [timdorr/spotifeed#26]
Any chance the generated feeds could include artwork? If not for each episode the individual one maybe at least the podcast's general one

**Comment by timdorr** [comment]
The image is included on the feed: https://github.com/timdorr/spotifeed/blob/master/spotifeed.rb#L89

If it's not showing up on your app, that would be an issue with your particular podcasting app. That is the only image tag I'm aware of, other than embedding it in the description, which has its own downsides.

**Comment by distantnative** [comment]
Using Castor which is very popular and has no problems with all other feeds, so don't know if that's really a problem of the app but the feed
