### ISSUE TITLE
Add <itunes:block> to the feed's channel

### ISSUE THREAD

**Issue by eazyliving** [timdorr/spotifeed#27]
Hiho!

To prevent independent podcast directories from listing the feeds generated, you might want to add 

`<itunes:block>yes</itunes:block>
`

to the feed's channels.

**Comment by timdorr** [comment]
Thanks! I didn't know about that tag. Added in 508fe3f.

**Comment by albertopasqualetto** [comment]
The problem with this is that Google Podcast is not going to support it (if added through the URL).
