### ISSUE TITLE
Spotifeed not working with overcast?

### ISSUE THREAD

**Issue by tundrablasen** [timdorr/spotifeed#28]
So I added a Spotify original podcast to overcast. Initially everything worked flawlessly. Just the update does not seem to work. Today a nEw episode was added and is visible in Spotify. But not in overcast.

i saw that pocket casts blocked the spotifeed url. Maybe overcast as well? Or are they grabbing directly from the rss url

**Comment by timdorr** [comment]
Which podcast are you trying to use?

**Comment by tundrablasen** [comment]
> Which podcast are you trying to use?

https://open.spotify.com/show/0clGHleJDnSMbRE1ytXk9w?si=uzm5uCq5Trm3TIiTlOnYYA

https://open.spotify.com/show/5JYitG4bOM3sVmAQRdX1Na?si=LvESU9pGT5e5yatRL-qZfA

**Comment by timdorr** [comment]
Both show the latest episodes that I can see in their feeds:

https://spotifeed.timdorr.com/0clGHleJDnSMbRE1ytXk9w    
https://spotifeed.timdorr.com/5JYitG4bOM3sVmAQRdX1Na

As far as I know, Overcast doesn't use a central service for feeds, so they wouldn't have a means to block Spotifeed. However, unless it's giving some sort of error message somewhere, this would be a support issue for Overcast, not Spotifeed.
