### ISSUE TITLE
Issue with Last Podcast on the Left

### ISSUE THREAD

**Issue by thedukesww** [timdorr/spotifeed#32]
I have noticed while trying to use this, that Last Podcast on the Left no longer works. It gets the show description, but is unable to find/download any audio file for that episode. 
https://open.spotify.com/show/3yZg2MCkf31pPXiG4nznrg

https://spotifeed.timdorr.com/3yZg2MCkf31pPXiG4nznrg

App: AntennaPod
OS: Android

**Comment by thedukesww** [comment]
nvm see it's dead

**Comment by Thaler1** [comment]
what was the fix for this?

**Comment by thedukesww** [comment]
Spotify changed their structure. Spotify made it impossible for now.
