### ISSUE TITLE
Self-hosted version that stores audio?

### ISSUE THREAD

**Issue by Vortec4800** [timdorr/spotifeed#33]
Let's say one wanted to host this privately somewhere and have the server download the mp4 chunks, convert them to a normal audio file, and host them for personal consumption. Might this functionality already exist somewhere?

**Comment by timdorr** [comment]
Nope, it's actually Widevine encrypted audio data (my initial assessment was wrong). So, if you want to break that encryption for all of Spotify, go right ahead. It's not something I'm looking to get involved with myself.
