### ISSUE TITLE
Episodes missing on Podcast Republic app

### ISSUE THREAD

**Issue by ofrayechiel** [timdorr/spotifeed#35]
Hi, really cool idea.
Any idea why I can't see the episodes on Podcast Republic?

example: 
https://spotifeed.timdorr.com/5F6UhVYHc5BPXEJ9kbb5W6
![IMG_20210813_102007](https://user-images.githubusercontent.com/16244726/129319847-5983ed29-4e46-4b09-be00-3e8524c1418e.jpg)

thank you :)

**Comment by timdorr** [comment]
This project is discontinued.
