### ISSUE TITLE
Doesn't seem to work anymore

### ISSUE THREAD

**Issue by flipper2gv** [timdorr/spotifeed#5]
The feed you created is really cool. But, it seemed to stop working with the last episode I can see being the "End of the World #2".

I use Pocket Cast. On desktop, it looks like this:
![image](https://user-images.githubusercontent.com/8779740/99002663-c9c58d80-250a-11eb-900c-6a9ac246d47b.png)

**Comment by timdorr** [comment]
Pocket Casts has been asked by Spotify to block Spotifeed. If you want to use it with Pocket Casts, you'll need to set up your own instance of this app. Otherwise, you'll need to switch to a different podcast app.

**Comment by flipper2gv** [comment]
Alright thanks man

**Comment by davidfregoli** [comment]
I managed to run the app locally and works for all other shows but I get `Not a valid show` for JRE

**Comment by timdorr** [comment]
Perhaps you cached bad data in Redis temporarily? I'd clear it out and give it another go.

**Comment by davidfregoli** [comment]
yeah that was the issue. still, for some reason PC doesn't recognize any of my feeds while Podcast Addict works fine, even jre.
anyway, I was able to make PC work by plugging your feed into an RSS aggregator.

**Comment by SEQUOiA87** [comment]
> Pocket Casts has been asked by Spotify to block Spotifeed. If you want to use it with Pocket Casts, you'll need to set up your own instance of this app. Otherwise, you'll need to switch to a different podcast app.

I think this should go into the readme.
