### ISSUE TITLE
The only missing information is the language tag

### ISSUE THREAD

**Issue by theboubougne** [timdorr/spotifeed#6]
If the language information could be extracted from the Spotify API it would be great!

**Comment by timdorr** [comment]
Right now I'm hard-coding to the US market, which might limit some non-English options: https://github.com/timdorr/spotifeed/blob/b37e9b29097514fd0e68e248a3d02b7462c307da/spotifeed.rb#L39

The only other issue is the language code that Spotify returns is different than the one the RSS spec uses. I'm not sure of the best way to translate between the two.

**Comment by theboubougne** [comment]
Do you have some examples of the language code returned by Spotify?

**Comment by timdorr** [comment]
[According to their API](https://developer.spotify.com/documentation/web-api/reference/shows/get-a-show/):
```json
  "languages" : [ "sv" ],
```

**Comment by theboubougne** [comment]
If this is for a podcast in Swedish then this is perfect. If you can add
this to the language tag that will be really helpful

**Comment by timdorr** [comment]
Ah, I didn't bother checking against the actual API with other content. It appears they use compatible codes (`en-US` for English).

Just pushed that out, but it'll take a little while to show up in the feeds with all the caching I have in place. Give it a day or two :)

**Comment by theboubougne** [comment]
If they provide the full language like with us english it's better but the
2 characters.iso language is enough

Thanks
