### ISSUE TITLE
Docs for self hosted version

### ISSUE THREAD

**Issue by Latz** [timdorr/spotifeed#7]
Some docs about installation and usage on a self hosted system would be nice. Not everybody (inlcuding me) is familiar with running Ruby apps, especially as a web service.

**Comment by hdlineage** [comment]
better yet, if we can make this into a docker container.

**Comment by timdorr** [comment]
It still requires a Redis instance, so a single Docker container won't be enough by itself. However, that should at least be documented somewhere :)

**Comment by davidfregoli** [comment]
Made it work with this Dockerfile:
```
FROM ruby:2.7.2
RUN git clone https://github.com/timdorr/spotifeed
WORKDIR /spotifeed
RUN git checkout a105f0956b33444c71a47a1cddff44f12b77c297
RUN bundle install
EXPOSE 8083
RUN apt-get update
RUN apt-get upgrade
RUN apt-get install redis-server -y
CMD puma -p 8083 & redis-server
```
then ran
```
docker build . -t spotifeed
docker run -d --name spotifeed -p 8083:8083 -e SPOTIFY_CLIENT_ID=YOUR_SPOTIFY_CLIENT_ID -e SPOTIFY_CLIENT_SECRET=YOUR_SPOTIFY_CLIENT_SECRET spotifeed
```

**Comment by miharekar** [comment]
A simpler alternative approachable to even more people would be to add a [deply to heroku button](https://devcenter.heroku.com/articles/heroku-button).

All you then need is to add your 2 env vars (`SPOTIFY_CLIENT_ID` and `SPOTIFY_CLIENT_SECRET`) in heroku which you can get from [Spotify dashboard](https://developer.spotify.com/dashboard/applications).

**Comment by timdorr** [comment]
While I currently host this on Heroku, I'll be moving over to my own startup, [Spaceship](https://spaceship.run/), very soon. So, for entirely selfish reasons, I won't be adding a Heroku button :)

**Comment by FunctionalHacker** [comment]
Thanks for the dockerfile, @davidfregoli! This got me up and running in a few minutes. I have one question, does the app need a persistent volume, meaning does spotifeed cache its RSS feeds somewhere?

**Comment by timdorr** [comment]
Just in Redis. I also use Cloudflare to do additional caching, but that's optional.

**Comment by cubajashi** [comment]
Can someone go into detail please? I don't use docker nether ruby. What are the equals to 
```
RUN bundle install
CMD puma -p 8083 & redis-server
``` 
inside 'normal' linux container?

1. How do i compile it? 
```
user@container spotifeed]$ rake
rake aborted!
Don't know how to build task 'default' (See the list of available tasks with `rake --tasks`)

(See full trace by running task with --trace)
[user@container spotifeed]$ rake --tasks
rake console  # Open an IRB session
```

2. How do i run it with redis?
