### ISSUE TITLE
Only showing episodes from September 15, 2020 and newer

### ISSUE THREAD

**Issue by atticusmatticus** [timdorr/spotifeed#8]
I'm using your code to access JRE from Spotify though Apple podcasts. When I try to find older episodes however they do not show past September 15, 2020.

There are many older episodes available on Spotify but they don't show up in the Apple Podcasts app. Everything else is working perfectly though. Shown below is the lowest I can scroll in the "See all Episodes" section of the podcast app.

<img width="1024" alt="Screen Shot 2020-12-27 at 16 15 58" src="https://user-images.githubusercontent.com/20863400/103180804-e1f53000-485e-11eb-89b1-47f72b7c93ea.png">

**Comment by swedejesus** [comment]
Try another podcast app (not Pocketcasts). Spotify is going after the podcast app and blocks spotifeed-url.

**Comment by timdorr** [comment]
I only grab the most recent 50 episodes from any podcast. To get more involved additional API calls and I don't want to be rate limited or put too much load on Spotify's systems. To generate a feed that far back would require about 32 API calls per fetch, which is too much for me.

**Comment by lud-hu** [comment]
@atticusmatticus : If you're interested in old episodes of Joe Rogan's podcast you can import this in your podcast app: https://gist.github.com/lud-hu/6afff1d2dc01355be504e1686efaf47a 
I've made this list with #22

**Comment by atticusmatticus** [comment]
Thanks for this!

**Comment by svendjanis** [comment]
@lud-hu Can I import it to Apple Podcast app?

**Comment by lud-hu** [comment]
@svendjanis Sorry, I don't know whether Apple podcast can do this.

**Comment by atticusmatticus** [comment]
I also have this question, as far as I'm aware apple podcasts app can only add shows from URL or a normal search within the app. The posted url will not work but I'm not sure if there is a way to generate a usable url for importing the show...

any guidance would be appreciated, thank you.

**Comment by lud-hu** [comment]
If the apple app can handle URLs, you should be able to use the "raw" link of the gist:
https://gist.githubusercontent.com/lud-hu/6afff1d2dc01355be504e1686efaf47a/raw/0f416013893b97b91d1df82bff1db6ca0c80cc3e/joe-rogan-experience.xml

**Comment by atticusmatticus** [comment]
can confirm that this works, thank you @lud-hu

**Comment by svendjanis** [comment]
Thank you man
